### ISSUE TITLE
epub reader in dark mode keeps dark text on dark background

### ISSUE THREAD

**Issue by SergioMendolia** [biblioverse/biblioteca#155] opened 2024-08-14 16:50 UTC

**Comment by ragusa87** [comment] 2024-08-14 21:35
The css injected in the vue component can be edited directly from the twig template. However the style I wrote might be incompatible with the book's stylesheet. Do you have this issue with all books or only one ? (Sorry I can't reproduce the issue right now, I will try in the upcoming days)

Can you share the book with me?

**Comment by ragusa87** [comment] 2024-08-17 08:00
Fixed by https://github.com/biblioverse/biblioteca/pull/159

**Closed** 2024-08-18 11:06 UTC
